//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverterFrontend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversion
    {
        public int ConversionID { get; set; }
        public string SourceCurrency { get; set; }
        public string DestinationCurrency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ConvertedAmount { get; set; }
        public int ConversionId { get; set; }
        public Nullable<System.DateTime> DateConverted { get; set; }
    }
}
